apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: push-test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    tasks:
      - name: say-hello
        taskSpec:
          steps:
            - name: echo
              image: alpine
              script: echo "hello from push event"
